#!/usr/bin/env bash

export HOST='i686-elf'

export QEMUFLAGS='-vga virtio'

export CC=$HOST-gcc
export CFLAGS='-O2 -g'
export CPPFLAGS=''

export AS=$HOST-as
export AR=$HOST-ar

export PREFIX=/usr
export EXEC_PREFIX=$PREFIX
export BOOTDIR=/boot
export LIBDIR=$EXEC_PREFIX/lib
export INCLUDEDIR=$PREFIX/include

export SYSROOT="$(pwd)/sysroot"
export CC="$CC --sysroot=$SYSROOT"

if echo "$HOST" | grep -Eq -- '-elf($|-)'; then
  export CC="$CC -isystem=$INCLUDEDIR"
fi

echo 'Config applied' 

